import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PageHeader, SectionHeader } from "@/components/Common";
import { RegenerateButton } from "@/components/ActionButtons";
import { Code, Eye, Globe, Sparkles, Check } from "lucide-react";

const sections = [
  { id: "hero", name: "Hero", color: "from-violet-500 to-fuchsia-500" },
  { id: "problem", name: "Problem", color: "from-rose-500 to-orange-500" },
  { id: "solution", name: "Solution", color: "from-blue-500 to-cyan-500" },
  { id: "features", name: "Features", color: "from-emerald-500 to-teal-500" },
  { id: "pricing", name: "Pricing", color: "from-amber-500 to-orange-500" },
  { id: "testimonials", name: "Testimonials", color: "from-pink-500 to-rose-500" },
  { id: "faq", name: "FAQ", color: "from-indigo-500 to-violet-500" },
  { id: "cta", name: "CTA", color: "from-purple-500 to-fuchsia-500" },
];

export default function WebsiteBuilder() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Website Builder"
        description="A complete landing page generated by your Website Agent."
        action={
          <div className="flex gap-2">
            <Button variant="outline"><Code className="h-3.5 w-3.5 mr-1" /> Export React</Button>
            <Button variant="outline"><Eye className="h-3.5 w-3.5 mr-1" /> Preview</Button>
            <Button className="bg-gradient-aurora text-white shadow-glow"><Globe className="h-3.5 w-3.5 mr-1" /> Publish</Button>
          </div>
        }
      />

      <div className="grid lg:grid-cols-[280px_1fr] gap-6">
        <Card className="p-4 glass border-border h-fit lg:sticky lg:top-24">
          <SectionHeader title="Sections" />
          <div className="space-y-1">
            {sections.map((s) => (
              <div key={s.id} className="group flex items-center gap-3 p-2.5 rounded-xl hover:bg-muted/50 cursor-pointer">
                <div className={`h-7 w-7 rounded-lg bg-gradient-to-br ${s.color}`} />
                <span className="text-sm flex-1">{s.name}</span>
                <RegenerateButton />
              </div>
            ))}
          </div>
        </Card>

        <Card className="p-2 glass border-border overflow-hidden">
          <div className="rounded-xl border border-border overflow-hidden bg-background">
            {/* Browser bar */}
            <div className="flex items-center gap-2 px-3 h-8 border-b border-border bg-muted/30">
              <div className="h-2 w-2 rounded-full bg-destructive/50" />
              <div className="h-2 w-2 rounded-full bg-warning/50" />
              <div className="h-2 w-2 rounded-full bg-success/50" />
              <div className="ml-3 text-[10px] text-muted-foreground font-mono">fitflow.ai</div>
            </div>
            {/* Mini hero */}
            <div className="relative p-8 mesh-bg">
              <Badge variant="outline" className="rounded-full mb-4">AI-powered fitness</Badge>
              <h2 className="font-display text-2xl sm:text-4xl font-bold">Your AI personal trainer, <span className="gradient-text">on autopilot.</span></h2>
              <p className="text-muted-foreground mt-3 text-sm max-w-xl">Plans that adapt every single day to your performance, energy and goals. Real coach-level personalization at the price of a coffee.</p>
              <div className="flex gap-2 mt-4">
                <Button size="sm" className="bg-gradient-aurora text-white">Start free</Button>
                <Button size="sm" variant="outline">Watch demo</Button>
              </div>
            </div>
            {/* Mini features */}
            <div className="grid grid-cols-3 gap-3 p-6 border-t border-border">
              {["Adaptive plans", "AI coach chat", "Habit streaks"].map((f) => (
                <div key={f} className="text-xs flex items-start gap-2"><Check className="h-3.5 w-3.5 text-primary mt-0.5" />{f}</div>
              ))}
            </div>
            {/* Mini pricing */}
            <div className="p-6 border-t border-border bg-muted/20">
              <div className="text-xs font-display font-semibold mb-3">Pricing</div>
              <div className="grid grid-cols-3 gap-2">
                {[{n:"Free",p:"₹0"},{n:"Pro",p:"₹1,499"},{n:"Coach+",p:"₹4,999"}].map((p, i) => (
                  <div key={p.n} className={`p-3 rounded-lg border ${i===1?"border-primary bg-gradient-aurora/5":"border-border"}`}>
                    <div className="text-xs">{p.n}</div>
                    <div className="font-display font-bold">{p.p}</div>
                  </div>
                ))}
              </div>
            </div>
            {/* Mini CTA */}
            <div className="p-8 text-center border-t border-border bg-gradient-aurora/5">
              <div className="font-display font-semibold mb-2">Ready to transform?</div>
              <Button size="sm" className="bg-gradient-aurora text-white"><Sparkles className="h-3.5 w-3.5 mr-1" /> Start free</Button>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}
